import { Locale } from '@/src/types';

const en = {
  appName: 'Daily Plate', today: 'Today', plan: 'Plan', groceries: 'Groceries', progress: 'Progress', settings: 'Settings',
  welcome: 'Eat well, one plate at a time.', welcomeBody: 'A private food diary and meal planner for your everyday rhythm.', getStarted: 'Get started', language: 'Language', english: 'English', greek: 'Ελληνικά',
  dailyGoals: 'Daily goals', calories: 'Calories', protein: 'Protein', carbs: 'Carbs', fat: 'Fat', diet: 'Eating style', balanced: 'Balanced', vegetarian: 'Vegetarian', vegan: 'Vegan', excluded: 'Ingredients to avoid', excludedHint: 'e.g. peanuts, mushrooms', save: 'Save', cancel: 'Cancel',
  consumed: 'Consumed', remaining: 'remaining', addFood: 'Add food', breakfast: 'Breakfast', lunch: 'Lunch', dinner: 'Dinner', snack: 'Snack', noEntries: 'Nothing logged yet', logFirst: 'Add your first food to see your day take shape.', grams: 'grams', searchFoods: 'Search foods', searchOnline: 'Search online', scanBarcode: 'Scan barcode', manualFood: 'Create custom food', portion: 'Portion', logFood: 'Log food', close: 'Close', unknown: 'Unknown', cameraPermission: 'Camera permission is needed to scan a barcode.', barcodeNotFound: 'No product found for that barcode.', copy: 'Copy', copied: 'Copied', createRecipe: 'Create recipe', recipeName: 'Recipe name', recipeInstructions: 'Instructions', ingredients: 'Ingredients (one per line)', nutritionPerServing: 'Nutrition per serving', create: 'Create',
  generatePlan: 'Generate plan', regenerate: 'Regenerate', locked: 'Locked', lock: 'Lock', replace: 'Replace', logMeal: 'Log meal', planEmpty: 'No plan for this day yet.', planTotals: 'Plan totals', groceryList: 'Grocery list', groceryHint: 'Ingredients from your saved plan appear here.', allDone: 'Everything is checked off.', progressTitle: 'Your week at a glance', weight: 'Weight', addWeight: 'Add weight', kilograms: 'kg', exportData: 'Export data', importData: 'Import data', dataTools: 'Data tools', restoreWarning: 'Restoring replaces your local data. Continue?', saved: 'Saved', delete: 'Delete', previous: 'Previous day', next: 'Next day', meals: 'meals', noRecipes: 'Not enough recipes match these preferences.', shortfall: 'The plan is short of the target by', onlineAttribution: 'Online food data provided by Open Food Facts.',
  streak: 'day streak', best: 'best', water: 'Water', recents: 'Recent', favorites: 'Favorites', allFoods: 'All foods', add: 'Add', goalHit: 'Daily goal crushed! 🎉', almostThere: 'Almost there — keep going!', freshStart: 'Fresh start — log something tasty!', weekInsight: '7-day insight', loggedDays: 'days logged', avgDay: 'avg / day', bestStreak: 'Best streak', days30: '30 days', days7: '7 days', waterGoal: '2.0 L goal', logged: 'logged',
  morning: 'Good morning', afternoon: 'Good afternoon', evening: 'Good evening', goalBadge: 'GOAL 🎉', privateOnDevice: 'private on this device', ingredientExample: 'e.g. 150 g tomato', done: 'done', packagedFood: 'Packaged food',
  likedFoods: 'Foods you like', pickFoods: 'Tap to add your favourite foods', daysToPlan: 'Days to plan', mealsPerDay: 'Meals per day', dailyCalories: 'Daily calories', useProteinGoal: 'Match protein goal', generateProposal: 'Generate proposal', proposal: 'Proposed plan', savePlan: 'Save plan', planSaved: 'Plan saved for the selected days', addLiked: 'Add', remove: 'Remove', needFoods: 'Add at least one food you like first.', dayPlan: 'Day', groceryNote: 'Food-based rows list grams directly and do not expand into grocery ingredients.', searchFailed: 'Food search failed', noFoodsDb: 'No foods in the database yet — add one from Today → Add food → Create custom food.', noFoodMatch: 'No match — try another search.',
};

const el: typeof en = {
  appName: 'Daily Plate', today: 'Σήμερα', plan: 'Πλάνο', groceries: 'Ψώνια', progress: 'Πρόοδος', settings: 'Ρυθμίσεις',
  welcome: 'Τρώμε καλά, ένα πιάτο τη φορά.', welcomeBody: 'Ένα ιδιωτικό ημερολόγιο διατροφής και σχεδιαστής γευμάτων για κάθε μέρα.', getStarted: 'Ξεκινήστε', language: 'Γλώσσα', english: 'English', greek: 'Ελληνικά',
  dailyGoals: 'Ημερήσιοι στόχοι', calories: 'Θερμίδες', protein: 'Πρωτεΐνη', carbs: 'Υδατάνθρακες', fat: 'Λίπος', diet: 'Τρόπος διατροφής', balanced: 'Ισορροπημένη', vegetarian: 'Χορτοφαγική', vegan: 'Βίγκαν', excluded: 'Υλικά προς αποφυγή', excludedHint: 'π.χ. φιστίκια, μανιτάρια', save: 'Αποθήκευση', cancel: 'Ακύρωση',
  consumed: 'Καταναλώθηκαν', remaining: 'υπόλοιπο', addFood: 'Προσθήκη τροφής', breakfast: 'Πρωινό', lunch: 'Μεσημεριανό', dinner: 'Βραδινό', snack: 'Σνακ', noEntries: 'Δεν έχει καταχωρηθεί τίποτα', logFirst: 'Πρόσθεσε την πρώτη τροφή για να δεις τη μέρα σου.', grams: 'γραμμάρια', searchFoods: 'Αναζήτηση τροφών', searchOnline: 'Αναζήτηση online', scanBarcode: 'Σάρωση barcode', manualFood: 'Δημιουργία τροφής', portion: 'Μερίδα', logFood: 'Καταχώρηση', close: 'Κλείσιμο', unknown: 'Άγνωστο', cameraPermission: 'Χρειάζεται άδεια κάμερας για τη σάρωση barcode.', barcodeNotFound: 'Δεν βρέθηκε προϊόν για αυτό το barcode.', copy: 'Αντιγραφή', copied: 'Αντιγράφηκε', createRecipe: 'Δημιουργία συνταγής', recipeName: 'Όνομα συνταγής', recipeInstructions: 'Οδηγίες', ingredients: 'Υλικά (ένα ανά γραμμή)', nutritionPerServing: 'Διατροφικά ανά μερίδα', create: 'Δημιουργία',
  generatePlan: 'Δημιουργία πλάνου', regenerate: 'Νέο πλάνο', locked: 'Κλειδωμένο', lock: 'Κλείδωμα', replace: 'Αλλαγή', logMeal: 'Καταχώρηση γεύματος', planEmpty: 'Δεν υπάρχει πλάνο για αυτή τη μέρα.', planTotals: 'Σύνολο πλάνου', groceryList: 'Λίστα για ψώνια', groceryHint: 'Τα υλικά από το αποθηκευμένο πλάνο εμφανίζονται εδώ.', allDone: 'Όλα ολοκληρώθηκαν.', progressTitle: 'Η εβδομάδα σου με μια ματιά', weight: 'Βάρος', addWeight: 'Προσθήκη βάρους', kilograms: 'κιλά', exportData: 'Εξαγωγή δεδομένων', importData: 'Εισαγωγή δεδομένων', dataTools: 'Δεδομένα', restoreWarning: 'Η επαναφορά αντικαθιστά τα τοπικά δεδομένα. Συνέχεια;', saved: 'Αποθηκεύτηκε', delete: 'Διαγραφή', previous: 'Προηγούμενη μέρα', next: 'Επόμενη μέρα', meals: 'γεύματα', noRecipes: 'Δεν υπάρχουν αρκετές συνταγές με αυτές τις προτιμήσεις.', shortfall: 'Το πλάνο υπολείπεται του στόχου κατά', onlineAttribution: 'Τα online δεδομένα τροφών παρέχονται από το Open Food Facts.',
  streak: 'σερί ημερών', best: 'ρεκόρ', water: 'Νερό', recents: 'Πρόσφατα', favorites: 'Αγαπημένα', allFoods: 'Όλα τα τρόφιμα', add: 'Προσθήκη', goalHit: 'Έπιασες τον στόχο! 🎉', almostThere: 'Λίγο ακόμα — συνέχισε!', freshStart: 'Νέα αρχή — καταχώρησε κάτι νόστιμο!', weekInsight: 'Εικόνα 7 ημερών', loggedDays: 'ημέρες καταχώρησης', avgDay: 'μ.ό. / ημέρα', bestStreak: 'Καλύτερο σερί', days30: '30 ημέρες', days7: '7 ημέρες', waterGoal: 'στόχος 2.0 L', logged: 'καταχωρήθηκε',
  morning: 'Καλημέρα', afternoon: 'Καλό μεσημέρι', evening: 'Καλησπέρα', goalBadge: 'ΣΤΟΧΟΣ 🎉', privateOnDevice: 'ιδιωτικά σε αυτή τη συσκευή', ingredientExample: 'π.χ. 150 g ντομάτα', done: 'έτοιμα', packagedFood: 'Τυποποιημένο τρόφιμο',
  likedFoods: 'Αγαπημένες τροφές', pickFoods: 'Πάτα για να προσθέσεις αγαπημένες τροφές', daysToPlan: 'Ημέρες πλάνου', mealsPerDay: 'Γεύματα ανά ημέρα', dailyCalories: 'Ημερήσιες θερμίδες', useProteinGoal: 'Στόχος πρωτεΐνης', generateProposal: 'Πρόταση πλάνου', proposal: 'Προτεινόμενο πλάνο', savePlan: 'Αποθήκευση πλάνου', planSaved: 'Το πλάνο αποθηκεύτηκε', addLiked: 'Προσθήκη', remove: 'Αφαίρεση', needFoods: 'Πρόσθεσε πρώτα τουλάχιστον μία τροφή.', dayPlan: 'Ημέρα', groceryNote: 'Οι τροφές δείχνουν γραμμάρια και δεν αναλύονται σε υλικά για ψώνια.', searchFailed: 'Η αναζήτηση απέτυχε', noFoodsDb: 'Δεν υπάρχουν τροφές — πρόσθεσε μία από Σήμερα → Προσθήκη τροφής.', noFoodMatch: 'Καμία αντιστοιχία — δοκίμασε άλλη αναζήτηση.',
};

export type TranslationKey = keyof typeof en;
export const translations = { en, el };
export const tFor = (locale: Locale, key: TranslationKey) => translations[locale][key];
